version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/app
    environment:
      - ENVIRONMENT=development
    cpu_count: 6
    mem_limit: 8000000000
