version: '3'
services:
  web:
    image: hmstepanek/sqlinjection-tbcnn:1.0.2
    command: python -m tbcnn.tbcnn
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 10G
        reservations:
          devices:
            - capabilities: [gpu]
